# Generated by Django 6.0.1 on 2026-01-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='enrollmentzz_date',
        ),
        migrations.AddField(
            model_name='students',
            name='enrolment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
