# Generated by Django 6.0.1 on 2026-01-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Portfolio', '0002_remove_students_enrollmentzz_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
